### ISSUE TITLE
Any checkpoints for experimenting with the synthesis alone?

### ISSUE THREAD

**Issue by husnoo** [gvashkevich/tf-flowavenet#2]
Hi sorry if this isn't the best place to ask - have you got any checkpoint files you'd be willing to share so I could try to generate some sound and play with the code? I'm reluctant to train it from scratch at the moment because it's summer and my house gets really warm (and my GPU isn't even that fast so it'd have to run for a long time). I'll try to train it in winter, but for now it'd be nice to study the code and some data files.
thanks
Nawal

**Comment by ryhorv** [comment]
Hi. Unfortunately I can't share any checkpoints from my previous experiments because I used a proprietary dataset for training. But I'm going to train this model using the LJ-Speech dataset and share the results in a few weeks.

**Comment by husnoo** [comment]
Ah right thanks! How many iterations do you reckon you need to train it for before it starts to sound intelligible? I don't need it to sound realistic at this point, as I'm just experimenting.

**Comment by ryhorv** [comment]
After ~200k iterations you can get hoarse speech.

**Comment by husnoo** [comment]
Hi, did you have a chance to train the model with the LJ-Speech dataset by any chance?

**Comment by ryhorv** [comment]
Hi. Thanks for reminding. Started training today.

**Comment by husnoo** [comment]
Hi, did you manage to store the checkpoints?
